services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ./src/.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  postgres_data:
  redis_data: