"""add permissions

Revision ID: 6a75a5f6989d
Revises: 9f4146bb1322
Create Date: 2025-07-28 01:42:09.139499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a75a5f6989d'
down_revision: Union[str, Sequence[str], None] = '9f4146bb1322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id', name=op.f('pk_permission')),
    sa.UniqueConstraint('name', name=op.f('uq_permission_name'))
    )
    op.create_table('user_permission_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], name=op.f('fk_user_permission_association_permission_id_permission')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_user_permission_association_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name=op.f('pk_user_permission_association'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission_association')
    op.drop_table('permission')
    # ### end Alembic commands ###
