"""user info

Revision ID: 64c640e49863
Revises: a659d731cdba
Create Date: 2025-07-27 16:17:05.395408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c640e49863'
down_revision: Union[str, Sequence[str], None] = 'a659d731cdba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=15), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=15), nullable=False))
    op.add_column('user', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.drop_column('user', 'description')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
