"""user add unique

Revision ID: 9f4146bb1322
Revises: 2735381cbfa3
Create Date: 2025-07-27 23:00:05.598639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4146bb1322'
down_revision: Union[str, Sequence[str], None] = '2735381cbfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    # ### end Alembic commands ###
