"""add posts

Revision ID: 9a55643a28aa
Revises: 
Create Date: 2025-07-28 19:14:55.284345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a55643a28aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id', name=op.f('pk_permission')),
    sa.UniqueConstraint('name', name=op.f('uq_permission_name'))
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registration', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('last_visit', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('last_name', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('post',
    sa.Column('table_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_post_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id', name=op.f('pk_post'))
    )
    op.create_table('settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('theme', sa.Enum('black', 'white', 'auto', name='theme'), nullable=False),
    sa.Column('language', sa.Enum('english', 'russian', name='language'), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_settings_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_settings'))
    )
    op.create_table('user_permission_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.permission_id'], name=op.f('fk_user_permission_association_permission_id_permission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_user_permission_association_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', name=op.f('pk_user_permission_association'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission_association')
    op.drop_table('settings')
    op.drop_table('post')
    op.drop_table('user')
    op.drop_table('permission')
    # ### end Alembic commands ###
