"""first

Revision ID: a659d731cdba
Revises: 
Create Date: 2025-07-26 01:28:57.693273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a659d731cdba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registration', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('last_visit', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_user'))
    )
    op.create_table('settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('theme', sa.Enum('black', 'white', 'auto', name='theme'), nullable=False),
    sa.Column('language', sa.Enum('english', 'russian', name='language'), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], name=op.f('fk_settings_chat_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('user')
    # ### end Alembic commands ###
